default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: spineless_dev
  user: rails
  password: rubyskye

test:
  <<: *default
  database: spineless_test
  user: rails
  password: rubyskye

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
