# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 898237d0701e43ba54f4d42f3403b8d50eceece2ae2a9930ec953a8791dd6162addd1c931c031358f1edac30677846b991e0ea2e4024dfd22388a9513ac9a3ae

test:
  secret_key_base: dd4127b8f128969830ea971a30ec4e2e2ef570ce520dc18e43bd6ae4d320f1f10bc3ca58b0596819b7c3afbdf13522b6f086e8eab9a3d8389a0dbf27689e6506

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
